version: '3.7'
services:
  main:
    image: nathanforester321/main:latest
    build: ./main
    ports:
        - target: 5000
          published: 5000
    deploy:
      replicas: 1
  converter:
    image: nathanforester321/converter:latest
    build: ./converter
    ports:
        - target: 5001
          published: 5001
    deploy:
      replicas: 1
  prime:
    image: nathanforester321/prime:latest
    build: ./prime
    ports:
        - target: 5002
          published: 5002
    deploy:
      replicas: 1